import type { DefectEventType } from "@/generated/prisma/client"
import {
  PlusIcon,
  PlayIcon,
  SaveIcon,
  SendIcon,
  MessageSquareIcon,
  ReplyIcon,
  CheckIcon,
  RotateCcwIcon,
  XCircleIcon,
  UserIcon,
  CalendarIcon,
  PaperclipIcon,
  TrashIcon,
  FileTextIcon,
  ClipboardCheckIcon,
  ShieldAlertIcon,
  AlertTriangleIcon,
  SparklesIcon,
  EyeIcon,
  LightbulbIcon,
  BanIcon,
} from "lucide-react"

type IconComponent = typeof PlusIcon

export interface EventMeta {
  label: string
  description: string
  icon: IconComponent
  iconColor: string
}

export const EVENT_META: Record<DefectEventType, EventMeta> = {
  CREATED: { label: "Created", description: "Defect report created", icon: PlusIcon, iconColor: "text-blue-500" },
  EIGHT_D_STARTED: { label: "8D Started", description: "8D investigation started", icon: PlayIcon, iconColor: "text-green-500" },
  EIGHT_D_STEP_SAVED: { label: "8D Step Saved", description: "8D step progress saved", icon: SaveIcon, iconColor: "text-muted-foreground" },
  EIGHT_D_SUBMITTED: { label: "8D Submitted", description: "8D report submitted for review", icon: SendIcon, iconColor: "text-green-600" },
  REVIEW_COMMENT_ADDED: { label: "Comment Added", description: "Review comment added", icon: MessageSquareIcon, iconColor: "text-blue-500" },
  REVIEW_COMMENT_RESPONDED: { label: "Comment Response", description: "Review comment responded to", icon: ReplyIcon, iconColor: "text-blue-500" },
  REVIEW_COMMENT_RESOLVED: { label: "Comment Resolved", description: "Review comment resolved", icon: CheckIcon, iconColor: "text-green-500" },
  REVIEW_COMMENT_REOPENED: { label: "Comment Reopened", description: "Review comment reopened", icon: RotateCcwIcon, iconColor: "text-amber-500" },
  REVISION_REQUESTED: { label: "Revision Requested", description: "OEM requested a revision", icon: XCircleIcon, iconColor: "text-red-500" },
  APPROVED: { label: "Approved", description: "8D report approved", icon: CheckIcon, iconColor: "text-green-600" },
  OWNER_CHANGED: { label: "Owner Changed", description: "OEM owner changed", icon: UserIcon, iconColor: "text-muted-foreground" },
  SUPPLIER_ASSIGNEE_CHANGED: { label: "Assignee Changed", description: "Supplier assignee changed", icon: UserIcon, iconColor: "text-muted-foreground" },
  DUE_DATE_CHANGED: { label: "Due Date Changed", description: "SLA due date updated", icon: CalendarIcon, iconColor: "text-amber-500" },
  EVIDENCE_ADDED: { label: "Evidence Added", description: "Supporting evidence uploaded", icon: PaperclipIcon, iconColor: "text-blue-500" },
  EVIDENCE_REMOVED: { label: "Evidence Removed", description: "Evidence file removed", icon: TrashIcon, iconColor: "text-red-500" },
  PPAP_CREATED: { label: "PPAP Created", description: "PPAP submission request created", icon: FileTextIcon, iconColor: "text-blue-500" },
  PPAP_SUBMITTED: { label: "PPAP Submitted", description: "PPAP submitted for review", icon: SendIcon, iconColor: "text-green-600" },
  PPAP_APPROVED: { label: "PPAP Approved", description: "PPAP submission approved", icon: CheckIcon, iconColor: "text-green-600" },
  PPAP_REJECTED: { label: "PPAP Rejected", description: "PPAP submission rejected", icon: XCircleIcon, iconColor: "text-red-500" },
  PPAP_REVISION_REQUESTED: { label: "PPAP Revision Requested", description: "PPAP revision requested by OEM", icon: RotateCcwIcon, iconColor: "text-amber-500" },
  PPAP_CANCELLED: { label: "PPAP Cancelled", description: "PPAP request cancelled", icon: XCircleIcon, iconColor: "text-muted-foreground" },
  PPAP_DOCUMENT_UPLOADED: { label: "Document Uploaded", description: "PPAP document uploaded by supplier", icon: PaperclipIcon, iconColor: "text-blue-500" },
  PPAP_DOCUMENT_APPROVED: { label: "Document Approved", description: "PPAP document approved by OEM", icon: CheckIcon, iconColor: "text-green-500" },
  PPAP_DOCUMENT_REJECTED: { label: "Document Rejected", description: "PPAP document rejected by OEM", icon: XCircleIcon, iconColor: "text-red-500" },
  PPAP_DOCUMENT_REVISION_REQUESTED: { label: "Document Revision Requested", description: "PPAP document revision requested by OEM", icon: RotateCcwIcon, iconColor: "text-amber-500" },
  IQC_CREATED: { label: "IQC Created", description: "Incoming quality inspection created", icon: ClipboardCheckIcon, iconColor: "text-blue-500" },
  IQC_COMPLETED: { label: "IQC Completed", description: "Incoming quality inspection completed", icon: CheckIcon, iconColor: "text-green-500" },
  IQC_FAILED: { label: "IQC Failed", description: "Incoming quality inspection failed", icon: AlertTriangleIcon, iconColor: "text-red-500" },
  IQC_CHECKLIST_UPDATED: { label: "Checklist Updated", description: "IQC checklist item updated", icon: SaveIcon, iconColor: "text-muted-foreground" },
  IQC_CANCELLED: { label: "IQC Cancelled", description: "IQC inspection cancelled", icon: XCircleIcon, iconColor: "text-muted-foreground" },
  IQC_RESULT_SET: { label: "Result Set", description: "IQC inspection result set", icon: ClipboardCheckIcon, iconColor: "text-amber-500" },
  FMEA_CREATED: { label: "FMEA Created", description: "FMEA analysis created", icon: ShieldAlertIcon, iconColor: "text-amber-500" },
  FMEA_UPDATED: { label: "FMEA Updated", description: "FMEA analysis updated", icon: SaveIcon, iconColor: "text-muted-foreground" },
  FMEA_SUBMITTED: { label: "FMEA Submitted", description: "FMEA submitted for review", icon: SendIcon, iconColor: "text-blue-500" },
  FMEA_APPROVED: { label: "FMEA Approved", description: "FMEA analysis approved", icon: CheckIcon, iconColor: "text-green-600" },
  FMEA_REJECTED: { label: "FMEA Rejected", description: "FMEA analysis rejected", icon: XCircleIcon, iconColor: "text-red-500" },
  FMEA_REVISION_REQUESTED: { label: "FMEA Revision Requested", description: "FMEA revision requested by OEM", icon: RotateCcwIcon, iconColor: "text-amber-500" },
  FMEA_CANCELLED: { label: "FMEA Cancelled", description: "FMEA analysis cancelled", icon: BanIcon, iconColor: "text-muted-foreground" },
  FIELD_DEFECT_CREATED: { label: "Field Defect Created", description: "Field defect report created", icon: PlusIcon, iconColor: "text-blue-500" },
  FIELD_DEFECT_STATUS_CHANGED: { label: "Status Changed", description: "Field defect status updated", icon: SaveIcon, iconColor: "text-muted-foreground" },
  FIELD_DEFECT_SUPPLIER_ASSIGNED: { label: "Supplier Assigned", description: "Supplier assigned to field defect", icon: UserIcon, iconColor: "text-blue-500" },
  FIELD_DEFECT_CONVERTED_TO_8D: { label: "Converted to 8D", description: "Field defect converted to 8D report", icon: SendIcon, iconColor: "text-emerald-500" },
  FIELD_DEFECT_COMMENT_ADDED: { label: "Comment Added", description: "Comment added to field defect", icon: MessageSquareIcon, iconColor: "text-blue-500" },
  FIELD_DEFECT_ATTACHMENT_ADDED: { label: "Attachment Added", description: "File attached to field defect", icon: PaperclipIcon, iconColor: "text-blue-500" },
  FIELD_DEFECT_ATTACHMENT_REMOVED: { label: "Attachment Removed", description: "File removed from field defect", icon: TrashIcon, iconColor: "text-red-500" },
  FIELD_DEFECT_CLOSED: { label: "Closed", description: "Field defect closed", icon: CheckIcon, iconColor: "text-green-500" },
  FIELD_DEFECT_CANCELLED: { label: "Cancelled", description: "Field defect cancelled", icon: XCircleIcon, iconColor: "text-muted-foreground" },
  FIELD_DEFECT_ESCALATED: { label: "Escalated", description: "Field defect escalated", icon: AlertTriangleIcon, iconColor: "text-red-500" },
  FIELD_DEFECT_SLA_UPDATED: { label: "SLA Updated", description: "Field defect SLA deadline updated", icon: CalendarIcon, iconColor: "text-amber-500" },
  FIELD_DEFECT_CATEGORY_UPDATED: { label: "Category Updated", description: "Field defect classification updated", icon: SaveIcon, iconColor: "text-muted-foreground" },
  AI_CLASSIFICATION_GENERATED: { label: "AI Classification", description: "AI classification generated for field defect", icon: SparklesIcon, iconColor: "text-emerald-500" },
  AI_SUGGESTION_ACCEPTED: { label: "AI Accepted", description: "AI suggestion accepted", icon: CheckIcon, iconColor: "text-green-500" },
  AI_SUGGESTION_REJECTED: { label: "AI Rejected", description: "AI suggestion rejected", icon: XCircleIcon, iconColor: "text-red-500" },
  AI_8D_REVIEW_GENERATED: { label: "AI 8D Review", description: "AI review generated for 8D report", icon: SparklesIcon, iconColor: "text-emerald-500" },
  AI_8D_REVIEW_MARKED_REVIEWED: { label: "AI Review Reviewed", description: "AI 8D review marked as reviewed", icon: EyeIcon, iconColor: "text-emerald-500" },
  AI_8D_REVIEW_REJECTED: { label: "AI Review Rejected", description: "AI 8D review rejected", icon: XCircleIcon, iconColor: "text-red-500" },
  AI_ROOT_CAUSE_SUGGESTED: { label: "AI Root Cause", description: "AI root cause suggestion generated", icon: LightbulbIcon, iconColor: "text-amber-500" },
}