"use client"

import { useMounted } from "@/hooks/use-mounted"
import type { ReviewSection } from "./DefectDetailView"

interface EightDPrintViewProps {
  partNumber: string
  oemName: string
  supplierName: string
  sections: ReviewSection[]
  printId: string
}

export function EightDPrintView({ partNumber, oemName, supplierName, sections, printId }: EightDPrintViewProps) {
  const mounted = useMounted()

  if (!mounted) return null

  return (
    <div
      id={printId}
      style={{
        display: "block",
        position: "fixed",
        left: "-9999px",
        top: 0,
        width: "210mm",
        minHeight: "297mm",
      }}
    >
      <div
        style={{
          padding: "20px",
          fontFamily: "Arial, Helvetica, sans-serif",
          fontSize: "12px",
          color: "#000",
          background: "#fff",
        }}
      >
        {/* Header */}
        <div
          style={{
            borderBottom: "2px solid #333",
            paddingBottom: "16px",
            marginBottom: "24px",
          }}
        >
          <h1 style={{ fontSize: "20px", fontWeight: "bold", margin: 0 }}>
            8D Report — {partNumber}
          </h1>
          <div style={{ marginTop: "8px", display: "flex", gap: "24px" }}>
            <div>
              <strong>OEM:</strong> {oemName}
            </div>
            <div>
              <strong>Supplier:</strong> {supplierName}
            </div>
          </div>
        </div>

        {/* Sections */}
        {sections.map((section) => (
          <div
            key={section.stepId}
            style={{ marginBottom: "20px", pageBreakInside: "avoid" }}
          >
            <h2
              style={{
                fontSize: "14px",
                fontWeight: "bold",
                marginBottom: "8px",
                borderBottom: "1px solid #ccc",
                paddingBottom: "4px",
              }}
            >
              {section.label}
            </h2>
            {section.headers && section.rows && section.rows.length > 0 ? (
              <table
                style={{
                  width: "100%",
                  borderCollapse: "collapse",
                  fontSize: "11px",
                }}
              >
                <thead>
                  <tr style={{ backgroundColor: "#f3f4f6" }}>
                    {section.headers.map((h, i) => (
                      <th
                        key={i}
                        style={{
                          border: "1px solid #d1d5db",
                          padding: "6px",
                          textAlign: "left",
                          fontWeight: 600,
                        }}
                      >
                        {h}
                      </th>
                    ))}
                  </tr>
                </thead>
                <tbody>
                  {section.rows.map((row, ri) => (
                    <tr key={ri}>
                      {row.cells.map((cell, ci) => (
                        <td
                          key={ci}
                          style={{
                            border: "1px solid #d1d5db",
                            padding: "6px",
                          }}
                        >
                          {cell}
                        </td>
                      ))}
                    </tr>
                  ))}
                </tbody>
              </table>
            ) : section.content ? (
              <div style={{ whiteSpace: "pre-wrap", lineHeight: 1.5 }}>
                {section.content}
              </div>
            ) : (
              <p style={{ color: "#6b7280", fontStyle: "italic" }}>
                Not provided
              </p>
            )}
          </div>
        ))}

        {/* Footer */}
        <div
          style={{
            marginTop: "32px",
            paddingTop: "12px",
            borderTop: "1px solid #ccc",
            textAlign: "center",
            fontSize: "10px",
            color: "#6b7280",
          }}
        >
          Generated by PlantQuality
        </div>
      </div>
    </div>
  )
}
