"use client"

import { useState } from "react"
import { jsPDF } from "jspdf"
import { DownloadIcon, Loader2Icon } from "lucide-react"
import { Button } from "@/components/ui/button"
import type { ReviewSection } from "./DefectDetailView"

interface ExportEightDButtonProps {
  defectId: string
  partNumber: string
  eightDData: ReviewSection[]
}

export function ExportEightDButton({
  defectId,
  partNumber,
  eightDData,
}: ExportEightDButtonProps) {
  const [isExporting, setIsExporting] = useState(false)

  if (!eightDData || eightDData.length === 0) {
    return null
  }

  const handleExport = () => {
    try {
      const doc = new jsPDF({ unit: "mm", format: "a4", orientation: "portrait" })
      const pageWidth = doc.internal.pageSize.getWidth()
      const margin = 15
      const usable = pageWidth - margin * 2
      let y = margin

      const addPageIfNeeded = (needed: number) => {
        const pageHeight = doc.internal.pageSize.getHeight()
        if (y + needed > pageHeight - margin) {
          doc.addPage()
          y = margin
        }
      }

      doc.setFont("helvetica", "bold")
      doc.setFontSize(18)
      doc.text(`8D Report \u2014 ${partNumber}`, margin, y)
      y += 8

      doc.setFont("helvetica", "normal")
      doc.setFontSize(10)

      const headerSection = eightDData.find((s) => s.stepId === "d1_team")
      if (headerSection) {
        const oemRow = headerSection.rows?.find((r) => r.cells[0]?.toLowerCase().includes("oem"))
        const supplierRow = headerSection.rows?.find((r) => r.cells[0]?.toLowerCase().includes("supplier"))
        const oemName = oemRow ? oemRow.cells[1] ?? "" : ""
        const supplierName = supplierRow ? supplierRow.cells[1] ?? "" : ""
        doc.text(`OEM: ${oemName}`, margin, y)
        doc.text(`Supplier: ${supplierName}`, margin + 80, y)
        y += 6
      }

      doc.setDrawColor(180)
      doc.line(margin, y, pageWidth - margin, y)
      y += 8

      for (const section of eightDData) {
        if (section.stepId === "d1_team" && section.rows && section.headers) {
          continue
        }

        addPageIfNeeded(12)
        doc.setFont("helvetica", "bold")
        doc.setFontSize(12)
        doc.text(section.label, margin, y)
        y += 5

        doc.setDrawColor(200)
        doc.line(margin, y, margin + usable, y)
        y += 4

        doc.setFont("helvetica", "normal")
        doc.setFontSize(9)

        if (section.rows && section.headers && section.rows.length > 0) {
          const colCount = section.headers.length
          const colW = usable / colCount

          doc.setFont("helvetica", "bold")
          doc.setFontSize(8)
          let x = margin
          for (let i = 0; i < section.headers.length; i++) {
            doc.text(section.headers[i], x + 1, y)
            x += colW
          }
          y += 5
          doc.setFont("helvetica", "normal")
          doc.setFontSize(8)

          for (const row of section.rows) {
            const lineH = 4.5
            let maxH = lineH
            for (let ci = 0; ci < row.cells.length; ci++) {
              const lines = doc.splitTextToSize(row.cells[ci] || "-", colW - 2)
              maxH = Math.max(maxH, lines.length * lineH)
            }

            addPageIfNeeded(maxH + 2)

            x = margin
            for (let ci = 0; ci < colCount; ci++) {
              const text = row.cells[ci] || "-"
              const lines = doc.splitTextToSize(text, colW - 2)
              doc.text(lines, x + 1, y)
              x += colW
            }
            y += maxH
          }
        } else if (section.content) {
          const lines = doc.splitTextToSize(section.content, usable)
          for (const line of lines) {
            addPageIfNeeded(5)
            doc.text(line, margin, y)
            y += 4
          }
        } else {
          doc.setTextColor(120)
          doc.text("Not provided", margin, y)
          doc.setTextColor(0)
          y += 5
        }

        y += 6
      }

      const pageCount = doc.getNumberOfPages()
      for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i)
        doc.setFont("helvetica", "normal")
        doc.setFontSize(8)
        doc.setTextColor(140)
        doc.text(
          "Generated by PlantQuality",
          pageWidth / 2,
          doc.internal.pageSize.getHeight() - 8,
          { align: "center" }
        )
        doc.setTextColor(0)
      }

      doc.save(`8D-Report-${partNumber}-${defectId}.pdf`)
    } catch (error) {
      console.error("PDF export failed:", error)
    } finally {
      setIsExporting(false)
    }
  }

  return (
    <Button
      variant="outline"
      size="sm"
      onClick={handleExport}
      disabled={isExporting}
    >
      {isExporting ? (
        <>
          <Loader2Icon className="mr-1.5 h-3.5 w-3.5 animate-spin" />
          Generating...
        </>
      ) : (
        <>
          <DownloadIcon className="mr-1.5 h-3.5 w-3.5" />
          Export PDF
        </>
      )}
    </Button>
  )
}